### PR TITLE
version update

### PR DESCRIPTION
**Pull request by xor2k**

### CODE REVIEW

**Comment by synapticarbors** [comment]
There are a few problems:

1. It doesn't look like a tar ball was released for this version -- there's only the wheel: https://pypi.org/project/npy-append-array/0.9.7/#files
2. You're going to need to update the `sha256` hash for the new build
3. If the license file is in the new release, you should delete the manually packaged copy.

**Comment by synapticarbors** [comment]
Once the tarball is uploaded to pypi, you could also wait for the bot to issue a PR to this feedstock to update it. You can certainly do it manually, but make sure you also rerender the recipe whenever you do an update:

https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks

**Comment by xor2k** [comment]
Okay, I've uploaded the source and the sha256sum of the source.

How to handle the license file (number 3 on your list)?

**Comment by synapticarbors** [comment]
@conda-forge-admin please rerender

**Comment by synapticarbors** [comment]
To remove the manually packaged license file just delete it from the `recipe` directory and then you can remove the comment in the `meta.yaml`. I also re-rendered the recipe using the call to the service.

**Comment by synapticarbors** [comment]
You still need the `license_file: LICENSE` line. Just remove the comment above it and delete the file `recipe/LICENSE` (the one in the directory with the `meta.yaml`).

**Comment by xor2k** [comment]
Okay, how about now?

**Comment by synapticarbors** [comment]
Looks good to me. You can go ahead and merge it.

**Comment by xor2k** [comment]
VS Code/git says "You don't have permissions to push to 'conda-forge/npy-append-array-feedstock' on GitHub." or is there a button I can click somewhere?

**Comment by synapticarbors** [comment]
Are you able to see the button here to merge the pull request? You should have permission since you're listed as a co-maintainer, but it doesn't look strange that you're not appearing in the CODEOWNERS file. I'll just merge it since I'm core and then hopefully that will fix up the permissions for next time.

**Comment by xor2k** [comment]
Okay, sounds nice! "conda install npy-append-array" still lists the old version 0.9.6. How long will it take until the new version is up?

**Comment by synapticarbors** [comment]
It takes maybe 30-45 minutes (if my memory serves me), for it to hit the CDN.  Once it's posted to the CDN you can get it via `conda install`.

**Comment by xor2k** [comment]
Yeah, cool! I've also just joined conda-forge.

**Comment by xor2k** [comment]
I've just made another update and pushed it. Will it be automatically processed and the package updated on conda-forge or is there anything else I need to do?

**Comment by synapticarbors** [comment]
Please make all updates through pull requests from a fork:

https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-recipes

It's probably a good idea to look through all of the maintainer's documentation.

**Pull request merged**
